# Generated by Django 3.2.5 on 2021-11-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(upload_to='services'),
        ),
    ]
